name: GitHub First Action

on:
  push:

jobs:
  first-run:
    runs-on: ubuntu-latest

    steps:
      - name: Display Hello World Message
        run: echo "Hello, World!"

      - name: Display Workflow Status
        run: echo "First job executed successfully."

  second-run:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Second Job
        run: |
          echo "Executing the second job..."
          echo "Second job completed successfully."
