name: github-first-action
on: push
jobs:
  first-run:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "hello world..!"
      - name: second-step
        run: echo "second steps performed"
  second-run:
    runs-on: ubuntu-latest
    steps:
      - name: my-second-job
        run: |
          echo "second job"
          echo "second job next line"
